"""Typed domain models for Grounded Response Composer (RSP-01).

Defines outcome categories, grounded facts, recovery suggestions, and response plans
used to construct deterministic and grounded Vietnamese responses.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ResponseOutcome(str, Enum):
    """Categorized response outcomes for public Agent output."""

    ALLOW_SUCCESS = "ALLOW_SUCCESS"
    ALLOW_FAILED = "ALLOW_FAILED"
    BLOCK_UNSAFE = "BLOCK_UNSAFE"
    BLOCK_UNAVAILABLE = "BLOCK_UNAVAILABLE"
    CONFIRM = "CONFIRM"
    NOT_VOICE_ACTIONABLE = "NOT_VOICE_ACTIONABLE"
    ANSWER = "ANSWER"
    UNKNOWN = "UNKNOWN"
    EXECUTION_ERROR = "EXECUTION_ERROR"


@dataclass(frozen=True)
class RecoverySuggestion:
    """Approved recovery suggestion for blocked or failed outcomes."""

    code: str
    message_vi: str


@dataclass(frozen=True)
class ResponsePlan:
    """Immutable response plan generated by the Grounded Response Composer."""

    outcome: ResponseOutcome
    text: str
    grounded_facts: dict[str, Any] = field(default_factory=dict)
    policy_reason: str | None = None
    rule_id: str | None = None
    reason_code: str | None = None
    recovery_suggestions: list[RecoverySuggestion] = field(default_factory=list)
    is_fallback: bool = False
    truncated: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Convert plan to dictionary representation."""
        return {
            "outcome": self.outcome.value,
            "text": self.text,
            "grounded_facts": dict(self.grounded_facts),
            "policy_reason": self.policy_reason,
            "rule_id": self.rule_id,
            "reason_code": self.reason_code,
            "recovery_suggestions": [s.message_vi for s in self.recovery_suggestions],
            "is_fallback": self.is_fallback,
            "truncated": self.truncated,
        }
