from pydantic import BaseModel, Field

class VehicleState(BaseModel):
    # Dynamics & Drive System
    speed_kmh: float = Field(default=0.0, description="Vehicle speed in km/h")
    gear: str = Field(default="P", description="Gear position: P, R, N, D")
    doors_locked: bool = Field(default=True, description="Door lock status")
    trunk_open: bool = Field(default=False, description="Trunk status")
    chargeport_open: bool = Field(default=False, description="Charge port door status")
    bonnet_open: bool = Field(default=False, description="Bonnet status")
    sunroof_open: bool = Field(default=False, description="Sunroof status")
    window_open: bool = Field(default=False, description="Window status")
    avh: bool = Field(default=True, description="Auto Vehicle Hold status")
    epb: bool = Field(default=True, description="Electric Parking Brake status")
    camp_mode_active: bool = Field(default=False, description="Camp mode status")
    pet_mode_active: bool = Field(default=False, description="Pet mode status")
    valet_mode_active: bool = Field(default=False, description="Valet mode status")
    profile: str = Field(default="USER", description="Driver profile: USER, GUEST, VALET")
    autopark_state: str = Field(default="INACTIVE", description="Autopark state: ACTIVE, INACTIVE")
    acc_state: str = Field(default="INACTIVE", description="Adaptive Cruise Control state: ACTIVE, INACTIVE")
    hands_on_steering_wheel: bool = Field(default=True, description="Hands on steering wheel status")
    hands_off_duration_seconds: float = Field(default=0.0, description="Duration in seconds with hands off steering wheel")
    folded_mirrors: bool = Field(default=False, description="Folded mirrors status")
    headlights_mode: str = Field(default="AUTO", description="Headlights mode: AUTO, HIGH, LOW, OFF")
    lowbeam_mode: str = Field(default="Off", description="Lowbeam mode: On, Off")
    fog_light: bool = Field(default=False, description="Fog light status")
    hazard_light: bool = Field(default=False, description="Hazard light status")
    esc: bool = Field(default=True, description="Electronic Stability Control status")
    tcs_active: bool = Field(default=False, description="Traction Control System active")
    wiper_speed: str = Field(default="OFF", description="Wiper speed: OFF, LOW, HIGH, MAX")
    drive_mode: str = Field(default="NORMAL", description="Drive mode: NORMAL, ECO, SPORT")
    lka_active: bool = Field(default=True, description="Lane Keeping Assist status")
    hud_active: bool = Field(default=True, description="HUD status")
    cornering_light_on: bool = Field(default=False, description="Cornering light status")
    interior_light_on: bool = Field(default=False, description="Interior light status")
    noti_center_open: bool = Field(default=False, description="Notification center status")
    
    # Seats & Interior Configuration (Anti-Submarining & Comfort)
    driver_seat_angle_deg: float = Field(default=95.0, description="Driver seat recline angle in degrees")
    passenger_seat_angle_deg: float = Field(default=95.0, description="Passenger seat recline angle in degrees")
    has_passenger: bool = Field(default=False, description="Passenger presence sensor")
    
    # Environment & Battery
    ambient_light: str = Field(default="DAY", description="Environmental light: DAY, NIGHT")
    rain_sensor: bool = Field(default=False, description="Rain detection sensor")
    battery_level: float = Field(default=85.0, description="Battery state of charge (%)")
    tire_pressure_psi: float = Field(default=32.0, description="Average tire pressure in PSI")