"""Grounded Response Composer (RSP-01).

Converts typed Guardrail decisions, execution results, and query facts into
grounded response plans and deterministic Vietnamese display messages.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from typing import Any

from vivi_agent.responses.catalog import (
    SUCCESS_CLAIM_KEYWORDS,
    format_relevant_state,
    get_approved_recovery_suggestions,
    get_catalog_template,
)
from vivi_agent.responses.models import (
    ResponseOutcome,
    ResponsePlan,
)

logger = logging.getLogger(__name__)

DEFAULT_MAX_RESPONSE_LENGTH = 150


class GroundedResponseComposer:
    """Composer responsible for producing strictly grounded, deterministic Vietnamese responses."""

    def __init__(self, max_length: int = DEFAULT_MAX_RESPONSE_LENGTH) -> None:
        self.max_length = max_length

    def compose_from_guardrail(
        self,
        decision: Mapping[str, Any],
        execution: Mapping[str, Any] | None = None,
        model_verbalization: str | None = None,
    ) -> ResponsePlan:
        """Compose a ResponsePlan from a Guardrail decision and optional execution result.

        Args:
            decision: Guardrail decision mapping containing outcome, rule_id, reason_code,
              relevant_state, etc.
            execution: Optional execution result mapping (e.g. containing success, message, error).
            model_verbalization: Optional verbalized text generated by provider model.

        Returns:
            Grounded ResponsePlan.
        """
        raw_outcome = decision.get("outcome", "UNKNOWN")
        reason_code = decision.get("reason_code")
        rule_id = decision.get("rule_id")
        policy_reason = decision.get("policy_reason")
        relevant_state = decision.get("relevant_state", {})

        # 1. Determine typed outcome and execution grounding
        outcome = self._resolve_guardrail_outcome(raw_outcome, execution)

        # 2. Extract grounded facts safely checking mapping instances
        grounded_facts: dict[str, Any] = {}
        if isinstance(relevant_state, Mapping):
            grounded_facts.update(relevant_state)
        
        answer = decision.get("answer")
        if isinstance(answer, Mapping):
            answer_facts = answer.get("facts")
            if isinstance(answer_facts, Mapping):
                grounded_facts.update(answer_facts)

        # 3. Retrieve recovery suggestions
        suggestions = get_approved_recovery_suggestions(outcome.value, reason_code)

        # 4. Generate deterministic template text
        fallback_text = self._build_fallback_text(
            outcome=outcome,
            decision=decision,
            execution=execution,
            reason_code=reason_code,
            policy_reason=policy_reason,
            relevant_state=relevant_state,
        )

        # 5. Evaluate model verbalization vs deterministic fallback
        final_text, is_fallback = self._select_text(
            outcome=outcome,
            model_verbalization=model_verbalization,
            fallback_text=fallback_text,
        )

        # 6. Apply length limit constraint
        final_text, truncated = self._apply_length_limit(final_text)

        return ResponsePlan(
            outcome=outcome,
            text=final_text,
            grounded_facts=grounded_facts,
            policy_reason=policy_reason,
            rule_id=rule_id,
            reason_code=reason_code,
            recovery_suggestions=suggestions,
            is_fallback=is_fallback,
            truncated=truncated,
        )

    # Stable vendor-neutral entry point. The older name remains compatible.
    compose_from_authorization = compose_from_guardrail

    def compose_from_query(
        self,
        query_result: Mapping[str, Any],
        model_verbalization: str | None = None,
    ) -> ResponsePlan:
        """Compose a ResponsePlan from a QueryResult mapping."""
        status = str(query_result.get("status", "UNKNOWN"))
        facts = query_result.get("facts", {})
        raw_text = query_result.get("response_text", "")

        if status == "ANSWER":
            outcome = ResponseOutcome.ANSWER
            fallback_text = (
                raw_text
                or (format_relevant_state(facts) if isinstance(facts, Mapping) else "")
                or get_catalog_template("ANSWER")
            )
        else:
            outcome = ResponseOutcome.UNKNOWN
            fallback_text = get_catalog_template("UNKNOWN")

        final_text, is_fallback = self._select_text(
            outcome=outcome,
            model_verbalization=model_verbalization,
            fallback_text=fallback_text,
        )

        final_text, truncated = self._apply_length_limit(final_text)

        return ResponsePlan(
            outcome=outcome,
            text=final_text,
            grounded_facts=dict(facts) if isinstance(facts, Mapping) else {},
            recovery_suggestions=get_approved_recovery_suggestions(outcome.value),
            is_fallback=is_fallback,
            truncated=truncated,
        )

    def _resolve_guardrail_outcome(
        self,
        raw_outcome: str,
        execution: Mapping[str, Any] | None,
    ) -> ResponseOutcome:
        """Resolve the grounded response outcome based on Guardrail decision and execution status."""
        if raw_outcome == "ALLOW":
            if execution is not None:
                # Check if execution failed
                exec_success = execution.get("success")
                exec_error = execution.get("error")
                if exec_success is False or exec_error is not None:
                    return ResponseOutcome.ALLOW_FAILED
            return ResponseOutcome.ALLOW_SUCCESS

        if raw_outcome == "BLOCK_UNSAFE":
            return ResponseOutcome.BLOCK_UNSAFE
        if raw_outcome == "BLOCK_UNAVAILABLE":
            return ResponseOutcome.BLOCK_UNAVAILABLE
        if raw_outcome == "CONFIRM":
            return ResponseOutcome.CONFIRM
        if raw_outcome == "NOT_VOICE_ACTIONABLE":
            return ResponseOutcome.NOT_VOICE_ACTIONABLE
        if raw_outcome == "ANSWER":
            return ResponseOutcome.ANSWER
        if raw_outcome == "UNKNOWN":
            return ResponseOutcome.UNKNOWN

        return ResponseOutcome.EXECUTION_ERROR

    def _build_fallback_text(
        self,
        outcome: ResponseOutcome,
        decision: Mapping[str, Any],
        execution: Mapping[str, Any] | None,
        reason_code: str | None,
        policy_reason: str | None,
        relevant_state: Any,
    ) -> str:
        """Build deterministic Vietnamese fallback text."""
        # Special case: ALLOW but execution failed
        if outcome == ResponseOutcome.ALLOW_FAILED:
            if execution and execution.get("message"):
                return str(execution["message"])
            if execution and execution.get("error"):
                err = execution["error"]
                if isinstance(err, Mapping) and err.get("message"):
                    return f"Thao tác không thành công: {err['message']}"
            return get_catalog_template("ALLOW_FAILED")

        # Special case: ALLOW success
        if outcome == ResponseOutcome.ALLOW_SUCCESS:
            if execution and execution.get("message"):
                return str(execution["message"])
            return get_catalog_template("ALLOW_SUCCESS")

        # Special case: ANSWER
        if outcome == ResponseOutcome.ANSWER:
            answer = decision.get("answer")
            if isinstance(answer, Mapping):
                facts = answer.get("facts")
                if isinstance(facts, Mapping):
                    formatted = format_relevant_state(facts)
                    if formatted:
                        return formatted
            return get_catalog_template("ANSWER")

        # General catalog lookup
        template = get_catalog_template(outcome.value, reason_code)

        # Append formatted relevant state if available for context
        if outcome in (ResponseOutcome.BLOCK_UNSAFE, ResponseOutcome.BLOCK_UNAVAILABLE) and isinstance(
            relevant_state, Mapping
        ):
            state_str = format_relevant_state(relevant_state)
            if state_str:
                return f"{template} ({state_str})"

        return template

    def _select_text(
        self,
        outcome: ResponseOutcome,
        model_verbalization: str | None,
        fallback_text: str,
    ) -> tuple[str, bool]:
        """Select between provider model verbalization and deterministic fallback.

        Enforces strict grounding validation:
        - If execution failed, model verbalization MUST NOT claim success.
        - If model verbalization is missing, empty, or whitespace, fallback is used.
        """
        if not model_verbalization or not model_verbalization.strip():
            return fallback_text, True

        verbalized = model_verbalization.strip()

        # Reject model verbalization if execution failed but verbalization falsely claims success
        if outcome == ResponseOutcome.ALLOW_FAILED:
            if any(kw in verbalized.lower() for kw in SUCCESS_CLAIM_KEYWORDS):
                logger.warning(
                    "Model verbalization falsely claimed success on failed execution. Falling back to deterministic message."
                )
                return fallback_text, True

        return verbalized, False

    def _apply_length_limit(self, text: str) -> tuple[str, bool]:
        """Truncate text if it exceeds self.max_length, ensuring clean boundaries."""
        if len(text) <= self.max_length:
            return text, False

        truncated_text = text[: self.max_length - 3].rstrip() + "..."
        return truncated_text, True
