"""Vehicle State Model, State Machine, and Event Store."""

from .model import (
    DEFAULT_VEHICLE_STATE,
    PIP_FIELD_NAMES,
    POWER_DEPENDENT_ADAS_INTENTS,
    REQUIRED_DOOR_IDS,
    VEHICLE_STATE_SCHEMA_VERSION,
    AccState,
    AmbientLight,
    AccessState,
    ActiveAction,
    ActiveActionPhase,
    AdasState,
    AutoparkState,
    CabinState,
    DoorPosition,
    DoorState,
    DriveMode,
    EnvironmentState,
    Gear,
    LightMode,
    LightingState,
    LockState,
    ModeState,
    MotionPhase,
    MotionState,
    PowerState,
    Profile,
    StateFieldProvenance,
    StateSource,
    TransmissionState,
    UiState,
    VehicleState,
    VehicleStateValidationError,
    pip_provenance,
)
from .presets import PRESETS, VehicleStatePreset, get_preset
from .events import ActorKind, StateChangedEvent, VehicleEventStore
from .machine import TransitionError, VersionConflictError, VehicleStateMachine

__all__ = [
    # --- VEH-01: Model ---
    "DEFAULT_VEHICLE_STATE",
    "PIP_FIELD_NAMES",
    "POWER_DEPENDENT_ADAS_INTENTS",
    "PRESETS",
    "REQUIRED_DOOR_IDS",
    "VEHICLE_STATE_SCHEMA_VERSION",
    "AccState",
    "AmbientLight",
    "AccessState",
    "ActiveAction",
    "ActiveActionPhase",
    "AdasState",
    "AutoparkState",
    "CabinState",
    "DoorPosition",
    "DoorState",
    "DriveMode",
    "EnvironmentState",
    "Gear",
    "LightMode",
    "LightingState",
    "LockState",
    "ModeState",
    "MotionPhase",
    "MotionState",
    "PowerState",
    "Profile",
    "StateFieldProvenance",
    "StateSource",
    "TransmissionState",
    "UiState",
    "VehicleState",
    "VehicleStatePreset",
    "VehicleStateValidationError",
    "get_preset",
    "pip_provenance",
    # --- VEH-02: State Machine & Events ---
    "ActorKind",
    "StateChangedEvent",
    "TransitionError",
    "VehicleEventStore",
    "VehicleStateMachine",
    "VersionConflictError",
]
